---
title: "RMarkdown_Practice"
output: html_document
---

## A function that generates sections

```{r Read in Data from MAster, include=FALSE}

library(readr)
library(dplyr)
library(readxl)

# -------------- MASTER path and file ----------
folder_x = "Y:/UCRTT/Prioritization/Step 2/Habitat Evaluation/"
master_file = "MASTER_Step2_REVIEWDRAFT_071321.xlsx"
MASTER_Data_path = paste(folder_x,master_file, sep="")   # Data from Okanogan EDT results
Habitat_Quality_Scores_MASTER = read_excel( MASTER_Data_path , sheet="Habitat Quality Pathway", skip=1)

# ----------------- Read in Shapefiles ---------------
# ------ updated with Okanogan EDT data layers -----------------
reaches_path = "Y:/UCRTT/Prioritization/Step 2/Data/GIS/Reaches/Reaches.shp"
reaches <- sf::st_read(reaches_path) # this shapefile does not show up properly
reaches <- sf::st_transform(reaches, 4326)

```


```{r Function for categorical output and color, include=FALSE}

# -------------- FUNCTION to generate category and color from REI score (1,3,5) ----------
REI_category_fxn = function(score_x){
  if(score_x == 1){
    category_x = "Unacceptable"
    color_x = "red"
  }else if(score_x > 3){
    category_x = "Adequate"
    color_x = "forestgreen"
  }else{
    category_x = "At Risk"
    color_x = "gold"
  }
  
  output_x = c(category_x, color_x)
  return(output_x)
}



# ---------- FUNCTION to generate color from a variable --------
colorize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color,
      x)
  } else x
}

# ----- Function to pull REI score/category/color based on A) ReachName and B) habitat attribute -----

Habitat_Quality_REI_metric_FUNCTION = function(ReachName_x, Habitat_Attribute_x){
  
  habitat_attribute_row_x <- Habitat_Quality_Scores_MASTER %>%
    filter(ReachName == ReachName_x) 
  
  habitat_attribute_numeric_output = habitat_attribute_row_x[1,Habitat_Attribute_x]
  
  # ----------- generate category (Unacceptable, At Risk, Adequate), color (red, yellow, green) -----
  category_output_x = REI_category_fxn(habitat_attribute_numeric_output)
  category_x = category_output_x[1]
  color_x = category_output_x[2]
  output_x = c(habitat_attribute_numeric_output, category_x, color_x)
  
  # ---------- if score is not present ----------
  if( habitat_attribute_numeric_output == "NA" ){
    output_x = c("NA", "not present", "black")
  }
  return(output_x)
  
}





colourise <- function(text, fg = "black", bg = NULL) {
  term <- Sys.getenv()["TERM"]
  colour_terms <- c("xterm-color","xterm-256color", "screen", "screen-256color")

  if(rcmd_running() || !any(term %in% colour_terms, na.rm = TRUE)) {
    return(text)
  }

  col_escape <- function(col) {
    paste0("\033[", col, "m")
  }

  col <- .fg_colours[tolower(fg)]
  if (!is.null(bg)) {
    col <- paste0(col, .bg_colours[tolower(bg)], sep = ";")
  }

  init <- col_escape(col)
  reset <- col_escape("0")
  paste0(init, text, reset)
}

.fg_colours <- c(
  "black" = "0;30",
  "blue" = "0;34",
  "green" = "0;32",
  "cyan" = "0;36",
  "red" = "0;31",
  "purple" = "0;35",
  "brown" = "0;33",
  "light gray" = "0;37",
  "dark gray" = "1;30",
  "light blue" = "1;34",
  "light green" = "1;32",
  "light cyan" = "1;36",
  "light red" = "1;31",
  "light purple" = "1;35",
  "yellow" = "1;33",
  "white" = "1;37"
)

.bg_colours <- c(
  "black" = "40",
  "red" = "41",
  "green" = "42",
  "brown" = "43",
  "blue" = "44",
  "purple" = "45",
  "cyan" = "46",
  "light gray" = "47"
)

rcmd_running <- function() {
  nchar(Sys.getenv('R_TESTS')) != 0
}

```


```{r}
library(pander)

create_section <- function(reach_x) {

   # Inserts "## Title (auto)"
   pander::pandoc.header(reach_x, level = 2)

   # Section contents
   # e.g. a random plot
  
   ### Coarse Substrate 
   print("Coarse Substrate ---- - - ")
   # ----------- generate category (Unacceptable, At Risk, Adequate), color (red, yellow, green) -----
   output_x = Habitat_Quality_REI_metric_FUNCTION(reach_x, "Coarse Substrate")
   REI_number_x = output_x[1]
   REI_category_x = output_x[2]
   REI_color_x = output_x[3]
  cat("  \n The **Cover- Wood** rating is **`r colorize(REI_category_x, REI_color_x)`** or  **`r colorize(REI_number_x, REI_color_x)`**.  \n")
    
  print( paste( 'The **Coarse Substrate** rating is:', REI_category_x, REI_number_x)  )

}
```



## Generate sections

```{r, echo=FALSE,message=FALSE,results="asis"}


reaches_list_x = reaches$ReachName[c(100,190,320,340,501)]

for (reach_x in reaches_list_x) {
   create_section(reach_x)
    cat("  \n The **Cover- Wood** rating is violets are <span style= 'color:blue'>blue</span> or  **`r colorize(1, 'green')`**.  \n")
  
}
```

# here's how to loop: https://stackoverflow.com/questions/36373630/how-to-create-a-loop-that-includes-both-a-code-chunk-and-text-with-knitr-in-r

```{r pressure,fig.width=6,echo=FALSE,message=FALSE,results="asis"}

attach(airquality)
for(i in unique(Month)) {
  cat("  \n###",  month.name[i], "Air Quaility  \n")
  #print(plot(airquality[airquality$Month == i,]))
  plot(airquality[airquality$Month == i,])
  cat("  \n")
}
```
